name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn --immutable
      - name: Test
        run: yarn test
